name: doc-check
on:
  push:
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
  pull_request:
    paths:
      - '**.html'
      - '**.css'
      - '**.js'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/restore-modules.sh
      - run: node verify_agent_doc.js
      - run: tools/html-validate "**/*.html"
