name: Documentation Check

on:
  pull_request:
    paths:
      - '**.html'
      - '.github/workflows/doc-check.yml'

jobs:
  doc-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy
      - name: Run tidy
        run: |
          find . -name '*.html' -print0 | xargs -0 tidy -qe

