name: fetch-static-tools
on:
  workflow_dispatch:

jobs:
  build-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (A) node_modules 오프라인 캐시
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: |
          mkdir -p offline_cache
          tar -czf offline_cache/node_modules.tar.gz node_modules
          echo "node_modules tar created"

      # (B) HTML 검사 도구 tidy (static)
      - run: |
          mkdir -p tools
          curl -sL https://github.com/htacg/tidy-html5/releases/download/5.8.0/tidy-linux64 \
            -o tools/tidy && chmod +x tools/tidy

      # (C) html-validate 독립 바이너리
      - run: |
          curl -sL https://github.com/html-validate/html-validate/releases/download/v8.0.0/html-validate-linux \
            -o tools/html-validate && chmod +x tools/html-validate

      # (D) link 검사 lychee 독립 바이너리
      - run: |
          curl -sL https://github.com/lycheeverse/lychee/releases/download/v0.15.1/lychee-v0.15.1-x86_64-unknown-linux-gnu.tar.gz \
            -o lychee.tar.gz && tar -xzf lychee.tar.gz -C tools && rm lychee.tar.gz

      # (E) Tailwind CLI (stand-alone)
      - run: |
          curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.0/tailwindcss-linux-x64 \
            -o tools/tailwindcss && chmod +x tools/tailwindcss

      # 커밋
      - name: Commit static tools
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email "actions@noreply.github.com"
          git add offline_cache/node_modules.tar.gz tools/
          git commit -m "chore: add static validators & node_modules cache" || echo "No changes"
          git push
