name: preflight-static
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tidy
        run: sudo apt-get update -y && sudo apt-get install -y tidy
      - name: Validate HTML
        run: |
          tidy -q -errors $(find . -name "*.html") 2> tidy-report.txt || true
          if grep -E "Error:" tidy-report.txt; then
            cat tidy-report.txt
            exit 1
          fi

      - name: Check links
        run: |
          docker run --rm -v $PWD:/data ghcr.io/lycheeverse/lychee \
            --offline --no-progress ./ | tee lychee.txt
          if grep -E "\[ERROR\]" lychee.txt; then
            exit 1
          fi
